services:
  web-app:
    build: .
    ports:
      - "8080:8080"
  timeseries-db:
    image: postgres:17-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db